# Configuration schema for Bento SDK module.

bento_sdk.settings:
  type: config_object
  label: 'Bento SDK settings'
  mapping:
    site_uuid:
      type: string
      label: 'Site UUID'
      constraints:
        Regex:
          pattern: '/^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[0-9a-f]{32})$/i'
          message: 'Site UUID must be in valid UUID format (with or without hyphens)'
    publishable_key:
      type: string
      label: 'Publishable Key'
    secret_key:
      type: string
      label: 'Secret Key (deprecated - use environment variable or secure storage)'
    enable_mail_routing:
      type: boolean
      label: 'Enable mail routing through Bento'

    default_author_email:
      type: string
      label: 'Default author email'
    enable_email_validation:
      type: boolean
      label: 'Enable email validation via Bento API'
    email_validation_cache_valid_duration:
      type: integer
      label: 'Cache duration for valid email validation results (seconds)'
    email_validation_cache_invalid_duration:
      type: integer
      label: 'Cache duration for invalid email validation results (seconds)'
    enable_rate_limiting:
      type: boolean
      label: 'Enable API rate limiting'
    max_requests_per_minute:
      type: integer
      label: 'Maximum API requests per minute'
    max_requests_per_hour:
      type: integer
      label: 'Maximum API requests per hour'
    max_test_emails_per_hour:
      type: integer
      label: 'Maximum test emails per hour'
    enable_circuit_breaker:
      type: boolean
      label: 'Enable circuit breaker pattern'
    circuit_breaker_failure_threshold:
      type: integer
      label: 'Number of failures before circuit breaker opens'
    circuit_breaker_timeout:
      type: integer
      label: 'Circuit breaker timeout in seconds'
    ssl_verification:
      type: boolean
      label: 'Enable SSL certificate verification'
    request_timeout:
      type: integer
      label: 'Request timeout in seconds'
    connection_timeout:
      type: integer
      label: 'Connection timeout in seconds'
    enable_request_id_tracking:
      type: boolean
      label: 'Enable request ID tracking for audit trails'